name: publish
permissions:
  contents: read
  id-token: write
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [25]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 10.14.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
      - name: Install modules
        run: |
          pnpm install
          pnpm run build
      - name: Unset NODE_AUTH_TOKEN
        run: unset NODE_AUTH_TOKEN
      - run: npm publish --access public --provenance
